// <auto-generated />
using System;
using CoffeeHouse.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeHouse.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeHouse.DAL.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("postal_code");

                    b.HasKey("Id")
                        .HasName("pk_address");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_address_city_id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_address_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_address_is_deleted");

                    b.ToTable("address", (string)null);
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.AddressTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("address_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("street");

                    b.HasKey("Id")
                        .HasName("pk_address_translation");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_address_translation_address_id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_address_translation_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_address_translation_is_deleted");

                    b.ToTable("address_translation", (string)null);
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<long>("ProvinceId")
                        .HasColumnType("bigint")
                        .HasColumnName("province_id");

                    b.HasKey("Id")
                        .HasName("pk_city");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_city_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_city_is_deleted");

                    b.HasIndex("ProvinceId")
                        .HasDatabaseName("ix_city_province_id");

                    b.ToTable("city", (string)null);
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.CityTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_city_translation");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_city_translation_city_id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_city_translation_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_city_translation_is_deleted");

                    b.ToTable("city_translation", (string)null);
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.Coffee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CoffeeTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("coffee_type_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.HasKey("Id")
                        .HasName("pk_coffee");

                    b.HasIndex("CoffeeTypeId")
                        .HasDatabaseName("ix_coffee_coffee_type_id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_coffee_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_coffee_is_deleted");

                    b.ToTable("coffee", (string)null);
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.CoffeePhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CoffeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("coffee_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.HasKey("Id")
                        .HasName("pk_coffee_photo");

                    b.HasIndex("CoffeeId")
                        .HasDatabaseName("ix_coffee_photo_coffee_id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_coffee_photo_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_coffee_photo_is_deleted");

                    b.ToTable("coffee_photo", (string)null);
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.CoffeeTranslation", b =>
                {
                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.Property<long>("CoffeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("coffee_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("LanguageId", "CoffeeId")
                        .HasName("pk_coffee_translation");

                    b.HasIndex("CoffeeId")
                        .HasDatabaseName("ix_coffee_translation_coffee_id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_coffee_translation_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_coffee_translation_is_deleted");

                    b.ToTable("coffee_translation", (string)null);
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.CoffeeType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.HasKey("Id")
                        .HasName("pk_coffee_type");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_coffee_type_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_coffee_type_is_deleted");

                    b.ToTable("coffee_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.CoffeeTypeTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CoffeeTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("coffee_type_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_coffee_type_translation");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_coffee_type_translation_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_coffee_type_translation_is_deleted");

                    b.HasIndex("CoffeeTypeId", "LanguageId")
                        .HasDatabaseName("ix_coffee_type_translation_coffee_type_id_language_id");

                    b.ToTable("coffee_type_translation", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CoffeeTypeId = 1L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 1,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Affogato"
                        },
                        new
                        {
                            Id = 2L,
                            CoffeeTypeId = 1L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 2,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Аффогато"
                        },
                        new
                        {
                            Id = 3L,
                            CoffeeTypeId = 1L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 3,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Աֆֆոքատո"
                        },
                        new
                        {
                            Id = 4L,
                            CoffeeTypeId = 2L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 1,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Americano"
                        },
                        new
                        {
                            Id = 5L,
                            CoffeeTypeId = 2L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 2,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Американо"
                        },
                        new
                        {
                            Id = 6L,
                            CoffeeTypeId = 2L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 3,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ամերիկանո"
                        },
                        new
                        {
                            Id = 7L,
                            CoffeeTypeId = 3L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 1,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Latte"
                        },
                        new
                        {
                            Id = 8L,
                            CoffeeTypeId = 3L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 2,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Латте"
                        },
                        new
                        {
                            Id = 9L,
                            CoffeeTypeId = 3L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 3,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Լատե"
                        },
                        new
                        {
                            Id = 10L,
                            CoffeeTypeId = 4L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 1,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cappuccino"
                        },
                        new
                        {
                            Id = 11L,
                            CoffeeTypeId = 4L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 2,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Капучино"
                        },
                        new
                        {
                            Id = 12L,
                            CoffeeTypeId = 4L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 3,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Կապուչինո"
                        },
                        new
                        {
                            Id = 13L,
                            CoffeeTypeId = 5L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 1,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mocha"
                        },
                        new
                        {
                            Id = 14L,
                            CoffeeTypeId = 5L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 2,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Моча"
                        },
                        new
                        {
                            Id = 15L,
                            CoffeeTypeId = 5L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 3,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Մոչա"
                        },
                        new
                        {
                            Id = 16L,
                            CoffeeTypeId = 6L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 1,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Macchiato"
                        },
                        new
                        {
                            Id = 17L,
                            CoffeeTypeId = 6L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 2,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Мачиато"
                        },
                        new
                        {
                            Id = 18L,
                            CoffeeTypeId = 6L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 3,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Մաչիատո"
                        },
                        new
                        {
                            Id = 19L,
                            CoffeeTypeId = 7L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 1,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Espresso"
                        },
                        new
                        {
                            Id = 20L,
                            CoffeeTypeId = 7L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 2,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Еспресо"
                        },
                        new
                        {
                            Id = 21L,
                            CoffeeTypeId = 7L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 3,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Եսպրեսօ"
                        },
                        new
                        {
                            Id = 22L,
                            CoffeeTypeId = 8L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 1,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Decaf"
                        },
                        new
                        {
                            Id = 23L,
                            CoffeeTypeId = 8L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 2,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Декаф"
                        },
                        new
                        {
                            Id = 24L,
                            CoffeeTypeId = 8L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 3,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Դեկաֆ"
                        },
                        new
                        {
                            Id = 25L,
                            CoffeeTypeId = 9L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 1,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Frappuccino"
                        },
                        new
                        {
                            Id = 26L,
                            CoffeeTypeId = 9L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 2,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Фрапучино"
                        },
                        new
                        {
                            Id = 27L,
                            CoffeeTypeId = 9L,
                            CreatedDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LanguageId = 3,
                            ModifyDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ֆրապուփչինո"
                        });
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.Error", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_error");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_error_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_error_is_deleted");

                    b.ToTable("error", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Oops! Something wen't wrong"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Not Authorized."
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Error while authorizing."
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "User Not Found."
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "User with provided username already exists."
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Entered data is not correct."
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Item Not Found."
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "The entered item already exists."
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Error. This component cannot be deleted."
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "The specified email address is already taken."
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ModifyDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Total error."
                        });
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.Province", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.HasKey("Id")
                        .HasName("pk_provinces");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_provinces_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_provinces_is_deleted");

                    b.ToTable("provinces", (string)null);
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.ProvinceTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<long>("ProvinceId")
                        .HasColumnType("bigint")
                        .HasColumnName("province_id");

                    b.HasKey("Id")
                        .HasName("pk_province_translation");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_province_translation_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_province_translation_is_deleted");

                    b.HasIndex("ProvinceId")
                        .HasDatabaseName("ix_province_translation_province_id");

                    b.ToTable("province_translation", (string)null);
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_users_created_date");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_users_is_deleted");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.UserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_expired");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modify_date");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_session");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_user_session_created_date");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_user_session_is_deleted");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_session_user_id");

                    b.ToTable("user_session", (string)null);
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.Address", b =>
                {
                    b.HasOne("CoffeeHouse.DAL.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_address_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.AddressTranslation", b =>
                {
                    b.HasOne("CoffeeHouse.DAL.Models.Address", "Address")
                        .WithMany("Translations")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_address_translation_address_address_id");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.City", b =>
                {
                    b.HasOne("CoffeeHouse.DAL.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_city_provinces_province_id");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.CityTranslation", b =>
                {
                    b.HasOne("CoffeeHouse.DAL.Models.City", "City")
                        .WithMany("Translations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_city_translation_city_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.Coffee", b =>
                {
                    b.HasOne("CoffeeHouse.DAL.Models.CoffeeType", "CoffeeType")
                        .WithMany()
                        .HasForeignKey("CoffeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_coffee_coffee_types_coffee_type_id");

                    b.Navigation("CoffeeType");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.CoffeePhoto", b =>
                {
                    b.HasOne("CoffeeHouse.DAL.Models.Coffee", "Coffee")
                        .WithMany("Files")
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coffee_photo_coffee_coffee_id");

                    b.Navigation("Coffee");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.CoffeeTranslation", b =>
                {
                    b.HasOne("CoffeeHouse.DAL.Models.Coffee", "Coffee")
                        .WithMany("Translations")
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coffee_translation_coffee_coffee_id");

                    b.Navigation("Coffee");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.CoffeeTypeTranslation", b =>
                {
                    b.HasOne("CoffeeHouse.DAL.Models.CoffeeType", "CoffeeType")
                        .WithMany("Translations")
                        .HasForeignKey("CoffeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coffee_type_translation_coffee_type_coffee_type_id");

                    b.Navigation("CoffeeType");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.ProvinceTranslation", b =>
                {
                    b.HasOne("CoffeeHouse.DAL.Models.Province", "Province")
                        .WithMany("Translations")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_province_translation_provinces_province_id");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.UserSession", b =>
                {
                    b.HasOne("CoffeeHouse.DAL.Models.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_session_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.Address", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.City", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.Coffee", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.CoffeeType", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.Province", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("CoffeeHouse.DAL.Models.User", b =>
                {
                    b.Navigation("UserSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
